---
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/scim/users/-
  value:
    name: feature-flags
    password: "((uaa_users_feature_flags_password))"
    groups:
      - cloud_controller.admin

- type: replace
  path: /variables/-
  value:
    name: uaa_users_feature_flags_password
    type: password
